/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

#pragma once

#include <AzCore/std/string/string.h>

namespace UnitTest
{
    namespace SdfModel
    {

        static AZStd::string GetSdfWithOneLink()
        {
            return "<?xml version=\"1.0\" ?>\n"
                   "<sdf version=\"1.6\">\n"
                   "  <model name=\"test_one_link\">\n"
                   "    <pose> 0 0 0 0 0 0</pose>\n"
                   "    <link name=\"link1\">\n"
                   "      <inertial>\n"
                   "        <inertia>\n"
                   "          <ixx>1.0</ixx>\n"
                   "          <ixy>0</ixy>\n"
                   "          <ixz>0</ixz>\n"
                   "          <iyy>1.0</iyy>\n"
                   "          <iyz>0</iyz>\n"
                   "          <izz>1.0</izz>\n"
                   "        </inertia>\n"
                   "        <mass>1.0</mass>\n"
                   "      </inertial>\n"
                   "      <visual name=\"link1_viz\">\n"
                   "        <geometry>\n"
                   "          <box>\n"
                   "            <size>1.0 2.0 3.0</size>\n"
                   "          </box>\n"
                   "        </geometry>\n"
                   "        <material>\n"
                   "          <ambient>0.0 0.3 0.6 1.0</ambient>\n"
                   "        </material>\n"
                   "      </visual>\n"
                   "      <collision name=\"link1_col\">\n"
                   "        <geometry>\n"
                   "          <box>\n"
                   "            <size>1.0 2.0 3.0</size>\n"
                   "          </box>\n"
                   "        </geometry>\n"
                   "      </collision>\n"
                   "      <sensor name=\"camera\" type=\"camera\">\n"
                   "        <pose>0 0 0 0 0 0</pose>\n"
                   "        <camera>\n"
                   "          <horizontal_fov>2.0</horizontal_fov>\n"
                   "          <image>\n"
                   "            <width>640</width>\n"
                   "            <height>480</height>\n"
                   "          </image>\n"
                   "          <clip>\n"
                   "            <near>0.01</near>\n"
                   "            <far>1000</far>\n"
                   "          </clip>\n"
                   "        </camera>\n"
                   "        <update_rate>10</update_rate>\n"
                   "      </sensor>\n"
                   "    </link>\n"
                   "  </model>\n"
                   "</sdf>\n";
        }

        static AZStd::string GetSdfWithTwoLinksAndJoint()
        {
            return "<?xml version=\"1.0\" ?>\n"
                   "<sdf version=\"1.6\">\n"
                   "  <model name=\"test_two_links\">\n"
                   "    <pose> 0 0 0 0 0 0</pose>\n"
                   "    <link name=\"link1\">\n"
                   "      <visual name=\"link1_viz\">\n"
                   "        <geometry>\n"
                   "          <box>\n"
                   "            <size>1.0 2.0 3.0</size>\n"
                   "          </box>\n"
                   "        </geometry>\n"
                   "      </visual>\n"
                   "      <collision name=\"link1_col\">\n"
                   "        <geometry>\n"
                   "          <box>\n"
                   "            <size>1.0 2.0 3.0</size>\n"
                   "          </box>\n"
                   "        </geometry>\n"
                   "      </collision>\n"
                   "      <sensor name=\"camera\" type=\"camera\">\n"
                   "        <pose>0 0 0 0 0 0</pose>\n"
                   "        <camera>\n"
                   "          <horizontal_fov>2.0</horizontal_fov>\n"
                   "          <image>\n"
                   "            <width>640</width>\n"
                   "            <height>480</height>\n"
                   "          </image>\n"
                   "          <clip>\n"
                   "            <near>0.01</near>\n"
                   "            <far>1000</far>\n"
                   "          </clip>\n"
                   "        </camera>\n"
                   "        <update_rate>10</update_rate>\n"
                   "      </sensor>\n"
                   "    </link>\n"
                   "    <link name=\"link2\">\n"
                   "      <visual name=\"link2_viz\">\n"
                   "        <geometry>\n"
                   "          <box>\n"
                   "            <size>1.0 2.0 3.0</size>\n"
                   "          </box>\n"
                   "        </geometry>\n"
                   "      </visual>\n"
                   "      <collision name=\"link2_col\">\n"
                   "        <geometry>\n"
                   "          <box>\n"
                   "            <size>1.0 2.0 3.0</size>\n"
                   "          </box>\n"
                   "        </geometry>\n"
                   "      </collision>\n"
                   "      <sensor name=\"laser\" type=\"ray\">\n"
                   "        <always_on>1</always_on>\n"
                   "        <visualize>1</visualize>\n"
                   "        <update_rate>20.0</update_rate>\n"
                   "        <pose>0 0 0 0 0 0</pose>\n"
                   "        <ray>\n"
                   "          <scan>\n"
                   "            <horizontal>\n"
                   "              <samples>640</samples>\n"
                   "              <resolution>1.0</resolution>\n"
                   "              <min_angle>-2.0</min_angle>\n"
                   "              <max_angle>2.5</max_angle>\n"
                   "            </horizontal>\n"
                   "          </scan>\n"
                   "          <range>\n"
                   "            <min>0.02</min>\n"
                   "            <max>10</max>\n"
                   "            <resolution>0.01</resolution>\n"
                   "          </range>\n"
                   "        </ray>\n"
                   "        <plugin name=\"laser_plug\" filename=\"librayplugin.so\"/>\n"
                   "      </sensor>\n"
                   "    </link>\n"
                   "    <joint name=\"joint\" type=\"revolute\">\n"
                   "      <parent>link1</parent>\n"
                   "      <child>link2</child>\n"
                   "      <pose>0 0.5 1 0 0 0</pose>\n"
                   "      <axis>\n"
                   "        <xyz>0 0 1</xyz>\n"
                   "      </axis>\n"
                   "    </joint>\n"
                   "    <plugin name=\"joint_state\" filename=\"libgazebo_ros_joint_state_publisher.so\">\n"
                   "      <ros>\n"
                   "        <argument>~/out:=joint_states</argument>\n"
                   "      </ros>\n"
                   "      <update_rate>30</update_rate>\n"
                   "      <joint_name>joint</joint_name>\n"
                   "    </plugin>\n"
                   "  </model>\n"
                   "</sdf>\n";
        }

    } // namespace SdfModel
} // namespace UnitTest
