
set(FILES
    Source/SimulationInterfacesROS2ModuleInterface.cpp
    Source/SimulationInterfacesROS2ModuleInterface.h
    Source/Clients/SimulationInterfacesROS2SystemComponent.cpp
    Source/Clients/SimulationInterfacesROS2SystemComponent.h
    Source/Interfaces/IROS2HandlerBase.h
    Source/Actions/SimulateStepsServer.cpp
    Source/Actions/SimulateStepsServer.h
    Source/Actions/ROS2ActionBaseClass.h
    Source/Services/ROS2ServiceBaseClass.h
    Source/Services/GetEntitiesServiceHandler.cpp
    Source/Services/GetEntitiesServiceHandler.h
    Source/Services/DeleteEntityServiceHandler.cpp
    Source/Services/DeleteEntityServiceHandler.h
    Source/Services/GetEntitiesServiceHandler.cpp
    Source/Services/GetEntitiesServiceHandler.h
    Source/Services/GetEntitiesStatesServiceHandler.cpp
    Source/Services/GetEntitiesStatesServiceHandler.h
    Source/Services/GetEntityStateServiceHandler.cpp
    Source/Services/GetEntityStateServiceHandler.h
    Source/Services/DeleteEntityServiceHandler.cpp
    Source/Services/DeleteEntityServiceHandler.h
    Source/Services/SetEntityStateServiceHandler.cpp
    Source/Services/SetEntityStateServiceHandler.h
    Source/Services/GetSpawnablesServiceHandler.cpp
    Source/Services/GetSpawnablesServiceHandler.h
    Source/Services/SpawnEntityServiceHandler.cpp
    Source/Services/SpawnEntityServiceHandler.h
    Source/Services/GetSimulationFeaturesServiceHandler.cpp
    Source/Services/GetSimulationFeaturesServiceHandler.h
    Source/Utils/RegistryUtils.cpp
    Source/Utils/RegistryUtils.h
    Source/Utils/Utils.h
)
